19/09/22 (11:57:25) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
19/09/22 (13:04:32) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
19/09/22 (14:24:03) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
19/09/22 (14:54:22) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
19/09/22 (17:58:59) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
19/09/22 (17:59:14) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
19/09/22 (22:10:38) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
20/09/22 (09:53:31) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
20/09/22 (09:54:40) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
20/09/22 (09:58:01) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
20/09/22 (11:46:54) | ERROR: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/gfuentes/.config/bpytop/themes'
